version: "2"
services:
  app:
    container_name: registration-microservice
    image: mamtabhardwaj12/registration-microservice
    restart: always
    build: .
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    container_name: registration-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
